#############################################################################
# Makefile for building: Todour
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  Todour.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile Todour.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DVER="\"\"" -DUGLOBALHOTKEY_NOEXPORT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -IQtAwesome/QtAwesome -IUGlobalHotkey -IUGlobalHotkey -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Todour1.0.0
DISTDIR = /home/runner/work/Todour/Todour/.tmp/Todour1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lxcb -lxcb-keysyms /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = QtAwesome/QtAwesome/QtAwesome.cpp \
		QtAwesome/QtAwesome/QtAwesomeAnim.cpp \
		UGlobalHotkey/ukeysequence.cpp \
		UGlobalHotkey/uglobalhotkeys.cpp \
		UGlobalHotkey/uexception.cpp \
		main.cpp \
		mainwindow.cpp \
		todotxt.cpp \
		todotablemodel.cpp \
		settingsdialog.cpp \
		aboutbox.cpp \
		quickadddialog.cpp qrc_QtAwesome.cpp \
		qrc_resources.cpp \
		moc_QtAwesome.cpp \
		moc_QtAwesomeAnim.cpp \
		moc_ukeysequence.cpp \
		moc_uglobalhotkeys.cpp \
		moc_mainwindow.cpp \
		moc_todotablemodel.cpp \
		moc_settingsdialog.cpp \
		moc_aboutbox.cpp \
		moc_quickadddialog.cpp
OBJECTS       = QtAwesome.o \
		QtAwesomeAnim.o \
		ukeysequence.o \
		uglobalhotkeys.o \
		uexception.o \
		main.o \
		mainwindow.o \
		todotxt.o \
		todotablemodel.o \
		settingsdialog.o \
		aboutbox.o \
		quickadddialog.o \
		qrc_QtAwesome.o \
		qrc_resources.o \
		moc_QtAwesome.o \
		moc_QtAwesomeAnim.o \
		moc_ukeysequence.o \
		moc_uglobalhotkeys.o \
		moc_mainwindow.o \
		moc_todotablemodel.o \
		moc_settingsdialog.o \
		moc_aboutbox.o \
		moc_quickadddialog.o
DIST          = Feature-move-show-all \
		Feature-AlwaysOnTop \
		Todour.desktop \
		autobuild/Todour.desktop \
		todour-latest.php \
		LICENSE \
		README \
		PRIVACY-POLICY \
		CHANGELOG \
		todour-latest_windows.php \
		todour-latest_mac.php \
		Feature_Url_Support \
		Feature-Advanced_filters.txt \
		Feature-follow_select \
		Feature-Enter_To_Search \
		Feature-customized-font-colors \
		Feature-Setup-ini \
		Feature-tagstrip \
		PLAN.md \
		todour.png \
		autobuild/package-windows.sh \
		autobuild/Setup.iss \
		autobuild/README.md \
		autobuild/build-todour-mac.pl \
		autobuild/todourdmg.json \
		autobuild/package-linux.sh \
		autobuild/DEBIAN_CONTROL_FILE.txt \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		QtAwesome/QtAwesome/QtAwesome.pri \
		UGlobalHotkey/uglobalhotkey-headers.pri \
		UGlobalHotkey/uglobalhotkey-sources.pri \
		UGlobalHotkey/uglobalhotkey-libs.pri \
		UGlobalHotkey/uglobalhotkey.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Todour.pro QtAwesome/QtAwesome/QtAwesome.h \
		QtAwesome/QtAwesome/QtAwesomeAnim.h \
		UGlobalHotkey/ukeysequence.h \
		UGlobalHotkey/uglobalhotkeys.h \
		UGlobalHotkey/uexception.h \
		UGlobalHotkey/hotkeymap.h \
		UGlobalHotkey/uglobal.h \
		mainwindow.h \
		todotxt.h \
		todotablemodel.h \
		settingsdialog.h \
		aboutbox.h \
		globals.h \
		quickadddialog.h \
		def.h QtAwesome/QtAwesome/QtAwesome.cpp \
		QtAwesome/QtAwesome/QtAwesomeAnim.cpp \
		UGlobalHotkey/ukeysequence.cpp \
		UGlobalHotkey/uglobalhotkeys.cpp \
		UGlobalHotkey/uexception.cpp \
		main.cpp \
		mainwindow.cpp \
		todotxt.cpp \
		todotablemodel.cpp \
		settingsdialog.cpp \
		aboutbox.cpp \
		quickadddialog.cpp
QMAKE_TARGET  = Todour
DESTDIR       = 
TARGET        = Todour


first: all
####### Build rules

Todour: ui_mainwindow.h ui_settingsdialog.h ui_aboutbox.h ui_quickadddialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Todour.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		QtAwesome/QtAwesome/QtAwesome.pri \
		UGlobalHotkey/uglobalhotkey-headers.pri \
		UGlobalHotkey/uglobalhotkey-sources.pri \
		UGlobalHotkey/uglobalhotkey-libs.pri \
		UGlobalHotkey/uglobalhotkey.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Todour.pro \
		QtAwesome/QtAwesome/QtAwesome.qrc \
		resources.qrc
	$(QMAKE) -o Makefile Todour.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
QtAwesome/QtAwesome/QtAwesome.pri:
UGlobalHotkey/uglobalhotkey-headers.pri:
UGlobalHotkey/uglobalhotkey-sources.pri:
UGlobalHotkey/uglobalhotkey-libs.pri:
UGlobalHotkey/uglobalhotkey.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Todour.pro:
QtAwesome/QtAwesome/QtAwesome.qrc:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile Todour.pro

qmake_all: FORCE


all: Makefile Todour

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents QtAwesome/QtAwesome/QtAwesome.qrc resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents QtAwesome/QtAwesome/QtAwesome.h QtAwesome/QtAwesome/QtAwesomeAnim.h UGlobalHotkey/ukeysequence.h UGlobalHotkey/uglobalhotkeys.h UGlobalHotkey/uexception.h UGlobalHotkey/hotkeymap.h UGlobalHotkey/uglobal.h mainwindow.h todotxt.h todotablemodel.h settingsdialog.h aboutbox.h globals.h quickadddialog.h def.h $(DISTDIR)/
	$(COPY_FILE) --parents QtAwesome/QtAwesome/QtAwesome.cpp QtAwesome/QtAwesome/QtAwesomeAnim.cpp UGlobalHotkey/ukeysequence.cpp UGlobalHotkey/uglobalhotkeys.cpp UGlobalHotkey/uexception.cpp main.cpp mainwindow.cpp todotxt.cpp todotablemodel.cpp settingsdialog.cpp aboutbox.cpp quickadddialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui settingsdialog.ui aboutbox.ui quickadddialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_QtAwesome.cpp qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_QtAwesome.cpp qrc_resources.cpp
qrc_QtAwesome.cpp: QtAwesome/QtAwesome/QtAwesome.qrc \
		/usr/lib/qt5/bin/rcc \
		QtAwesome/QtAwesome/fonts/fontawesome-4.7.0.ttf
	/usr/lib/qt5/bin/rcc -name QtAwesome QtAwesome/QtAwesome/QtAwesome.qrc -o qrc_QtAwesome.cpp

qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		todour.png
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_QtAwesome.cpp moc_QtAwesomeAnim.cpp moc_ukeysequence.cpp moc_uglobalhotkeys.cpp moc_mainwindow.cpp moc_todotablemodel.cpp moc_settingsdialog.cpp moc_aboutbox.cpp moc_quickadddialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_QtAwesome.cpp moc_QtAwesomeAnim.cpp moc_ukeysequence.cpp moc_uglobalhotkeys.cpp moc_mainwindow.cpp moc_todotablemodel.cpp moc_settingsdialog.cpp moc_aboutbox.cpp moc_quickadddialog.cpp
moc_QtAwesome.cpp: QtAwesome/QtAwesome/QtAwesome.h \
		QtAwesome/QtAwesome/QtAwesomeAnim.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/runner/work/Todour/Todour/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/runner/work/Todour/Todour -I/home/runner/work/Todour/Todour/QtAwesome/QtAwesome -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include QtAwesome/QtAwesome/QtAwesome.h -o moc_QtAwesome.cpp

moc_QtAwesomeAnim.cpp: QtAwesome/QtAwesome/QtAwesomeAnim.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/runner/work/Todour/Todour/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/runner/work/Todour/Todour -I/home/runner/work/Todour/Todour/QtAwesome/QtAwesome -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include QtAwesome/QtAwesome/QtAwesomeAnim.h -o moc_QtAwesomeAnim.cpp

moc_ukeysequence.cpp: UGlobalHotkey/ukeysequence.h \
		UGlobalHotkey/uexception.h \
		UGlobalHotkey/uglobal.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/runner/work/Todour/Todour/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/runner/work/Todour/Todour -I/home/runner/work/Todour/Todour/QtAwesome/QtAwesome -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include UGlobalHotkey/ukeysequence.h -o moc_ukeysequence.cpp

moc_uglobalhotkeys.cpp: UGlobalHotkey/uglobalhotkeys.h \
		UGlobalHotkey/ukeysequence.h \
		UGlobalHotkey/uexception.h \
		UGlobalHotkey/uglobal.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/runner/work/Todour/Todour/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/runner/work/Todour/Todour -I/home/runner/work/Todour/Todour/QtAwesome/QtAwesome -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include UGlobalHotkey/uglobalhotkeys.h -o moc_uglobalhotkeys.cpp

moc_mainwindow.cpp: mainwindow.h \
		UGlobalHotkey/uglobalhotkeys.h \
		UGlobalHotkey/ukeysequence.h \
		UGlobalHotkey/uexception.h \
		UGlobalHotkey/uglobal.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/runner/work/Todour/Todour/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/runner/work/Todour/Todour -I/home/runner/work/Todour/Todour/QtAwesome/QtAwesome -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_todotablemodel.cpp: todotablemodel.h \
		todotxt.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/runner/work/Todour/Todour/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/runner/work/Todour/Todour -I/home/runner/work/Todour/Todour/QtAwesome/QtAwesome -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include todotablemodel.h -o moc_todotablemodel.cpp

moc_settingsdialog.cpp: settingsdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/runner/work/Todour/Todour/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/runner/work/Todour/Todour -I/home/runner/work/Todour/Todour/QtAwesome/QtAwesome -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include settingsdialog.h -o moc_settingsdialog.cpp

moc_aboutbox.cpp: aboutbox.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/runner/work/Todour/Todour/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/runner/work/Todour/Todour -I/home/runner/work/Todour/Todour/QtAwesome/QtAwesome -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include aboutbox.h -o moc_aboutbox.cpp

moc_quickadddialog.cpp: quickadddialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/runner/work/Todour/Todour/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/runner/work/Todour/Todour -I/home/runner/work/Todour/Todour/QtAwesome/QtAwesome -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/home/runner/work/Todour/Todour/UGlobalHotkey -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.15.13/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.15.13/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include quickadddialog.h -o moc_quickadddialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_settingsdialog.h ui_aboutbox.h ui_quickadddialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_settingsdialog.h ui_aboutbox.h ui_quickadddialog.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_settingsdialog.h: settingsdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic settingsdialog.ui -o ui_settingsdialog.h

ui_aboutbox.h: aboutbox.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic aboutbox.ui -o ui_aboutbox.h

ui_quickadddialog.h: quickadddialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic quickadddialog.ui -o ui_quickadddialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

QtAwesome.o: QtAwesome/QtAwesome/QtAwesome.cpp QtAwesome/QtAwesome/QtAwesome.h \
		QtAwesome/QtAwesome/QtAwesomeAnim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtAwesome.o QtAwesome/QtAwesome/QtAwesome.cpp

QtAwesomeAnim.o: QtAwesome/QtAwesome/QtAwesomeAnim.cpp QtAwesome/QtAwesome/QtAwesomeAnim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtAwesomeAnim.o QtAwesome/QtAwesome/QtAwesomeAnim.cpp

ukeysequence.o: UGlobalHotkey/ukeysequence.cpp UGlobalHotkey/ukeysequence.h \
		UGlobalHotkey/uexception.h \
		UGlobalHotkey/uglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ukeysequence.o UGlobalHotkey/ukeysequence.cpp

uglobalhotkeys.o: UGlobalHotkey/uglobalhotkeys.cpp UGlobalHotkey/hotkeymap.h \
		UGlobalHotkey/ukeysequence.h \
		UGlobalHotkey/uexception.h \
		UGlobalHotkey/uglobal.h \
		UGlobalHotkey/uglobalhotkeys.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uglobalhotkeys.o UGlobalHotkey/uglobalhotkeys.cpp

uexception.o: UGlobalHotkey/uexception.cpp UGlobalHotkey/uexception.h \
		UGlobalHotkey/uglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uexception.o UGlobalHotkey/uexception.cpp

main.o: main.cpp mainwindow.h \
		UGlobalHotkey/uglobalhotkeys.h \
		UGlobalHotkey/ukeysequence.h \
		UGlobalHotkey/uexception.h \
		UGlobalHotkey/uglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		UGlobalHotkey/uglobalhotkeys.h \
		UGlobalHotkey/ukeysequence.h \
		UGlobalHotkey/uexception.h \
		UGlobalHotkey/uglobal.h \
		ui_mainwindow.h \
		todotablemodel.h \
		todotxt.h \
		settingsdialog.h \
		quickadddialog.h \
		aboutbox.h \
		globals.h \
		def.h \
		QtAwesome/QtAwesome/QtAwesome.h \
		QtAwesome/QtAwesome/QtAwesomeAnim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

todotxt.o: todotxt.cpp todotxt.h \
		def.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o todotxt.o todotxt.cpp

todotablemodel.o: todotablemodel.cpp todotablemodel.h \
		todotxt.h \
		globals.h \
		def.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o todotablemodel.o todotablemodel.cpp

settingsdialog.o: settingsdialog.cpp settingsdialog.h \
		ui_settingsdialog.h \
		globals.h \
		def.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsdialog.o settingsdialog.cpp

aboutbox.o: aboutbox.cpp aboutbox.h \
		ui_aboutbox.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutbox.o aboutbox.cpp

quickadddialog.o: quickadddialog.cpp quickadddialog.h \
		ui_quickadddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quickadddialog.o quickadddialog.cpp

qrc_QtAwesome.o: qrc_QtAwesome.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_QtAwesome.o qrc_QtAwesome.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_QtAwesome.o: moc_QtAwesome.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtAwesome.o moc_QtAwesome.cpp

moc_QtAwesomeAnim.o: moc_QtAwesomeAnim.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtAwesomeAnim.o moc_QtAwesomeAnim.cpp

moc_ukeysequence.o: moc_ukeysequence.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ukeysequence.o moc_ukeysequence.cpp

moc_uglobalhotkeys.o: moc_uglobalhotkeys.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uglobalhotkeys.o moc_uglobalhotkeys.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_todotablemodel.o: moc_todotablemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_todotablemodel.o moc_todotablemodel.cpp

moc_settingsdialog.o: moc_settingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsdialog.o moc_settingsdialog.cpp

moc_aboutbox.o: moc_aboutbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutbox.o moc_aboutbox.cpp

moc_quickadddialog.o: moc_quickadddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quickadddialog.o moc_quickadddialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

